### ISSUE TITLE
Is this a virus?

### ISSUE THREAD

**Issue by DrinkDeuchars** [tyoma/micro-profiler#27]
The install proceeds without error but as far as I can tell there is nothing installed on my system. The installation folder is empty and there are no program items nor VS integrations. I would guess micro-profiler is either completely broke or has deliberately compromised my system.

**Comment by tyoma** [comment]
micro-profiler is not an independent executable, but rather a dll that encapsulates performance collector, frontend and VisualStudio integration. The default install location is "<program-files>/gevorkyan.org/MicroProfiler". Once installed it adds context menus to VisualStudio so that in solution explorer it becomes possible to enable profiling for a project (dll or exe, static libs require manual changes in compiler options). Then later, when you start that exe or a program that loads your dll - the micro-profiler window automatically pops up.

If you're claiming that nothing is installed (you're not seeing the directory I mentioned), would you be able to run msiexec with logging enabled? This is how you can do it:
msiexec /i micro-profiler_x64.v1.1.591.0.msi /L*V micro-profiler.install.log

Thank you!

P.S. I've discovered that x86 version does not appear in "programs and features" of my Win10 machine (although it works fine). So if you installed it, you can uninstall it with:
 msiexec /x micro-profiler_x86.v1.1.591.0.msi

P.P.S. Btw, it doesn't support "visual studio 2017" yet. Maybe that's your case.

P.P.P.S If you have enough enthusiasm you can rebuild it from sources to see it is not a virus :)

**Comment by tyoma** [comment]
Was this helpful? Have you been able to collect the logs / locate micro-profiler in program files?..

**Comment by tyoma** [comment]
I'm closing this. No, this is not a virus - get sources, inspect and build it yourself, if you don't trust the published version :)
