### ISSUE TITLE
TF10122: The path '$/MyTeamProject/MyProject/$(MICROPROFILERDIR)/micro-profiler.initializer.cpp' contains a '$' at the beginning of a path component. Remove the '$' and try again.

### ISSUE THREAD

**Issue by icnocop** [tyoma/micro-profiler#42]
Hi.

Thank you for MicroProfiler.

When I right-click on my project and select "Enable Profiling", I get the following prompt:
![image](https://user-images.githubusercontent.com/507649/51519348-91087180-1dd5-11e9-9eb3-4d210d7fbd4b.png)

When I click on "Add the item", I get the following output in the "Source Control - Team Foundation" category of the Output window:
TF10122: The path '$/MyTeamProject/MyProject/$(MICROPROFILERDIR)/micro-profiler.initializer.cpp' contains a '$' at the beginning of a path component. Remove the '$' and try again.
MyProject.vcxproj, MyProject.vcxproj.filters have been automatically checked out for editing.
There is no working folder mapping for C:\Users\first.last\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\y45mosn5.hom.
There is no working folder mapping for C:\Users\first.last\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\y45mosn5.hom.

Visual Studio 2015.

Are those messages expected for a TFS source controlled project?

Thank you.

**Comment by tyoma** [comment]
Hi!

Addition of this file is only required to profile - it was never meant to be checked in to TFS (or any other source control). VisualStudio gives you this message since the file is located in a directory MicroProfiler installed to rather than in the directory which is nested under your controlled source root (you'll get it on any attempt to add a file that is not under controlled root). As of of now you can safely ignore this message (clicking 'Cancel add'). At some point I will remove the necessity to add this file.

thank you!

**Comment by icnocop** [comment]
Thank you for the explanation. It makes sense. 😊
