### ISSUE TITLE
UI incomplete

### ISSUE THREAD

**Issue by pk1954** [tyoma/micro-profiler#47]
Hi,
I installed micro-profiler, checked "Enable profiler" on my application, rebuild the solution and started the app. The profiler frontend shows up and I can see the colored ring, **but no text columns**. 

![screenshot](https://user-images.githubusercontent.com/25415300/61627866-200d1e00-ac81-11e9-906a-2e6e62be114f.jpg)

The ring is alive, it changes while the app is running. I can select segments, but no textual information is visible.
I use visual studio community 2019 version 16.1.6..
Any idea what I'm doing wrong?
Best regards
Peter

**Comment by tyoma** [comment]
Hi Peter!

To make sure the reason is what I think (inability to create ListView32 control, rather than apartment issue), please: start profiling, save the stats (in the pane's toolbar click save), then attempt to load saved statistics from Extensions/MicroProfiler/Open Statistics... (it may be grayed out for a while after the Studio startup).

thanks,
Artem

**Comment by tyoma** [comment]
Can you please try replacing extension dll with the one attached (while VisualStudio is not running)? You can find it among other extensions in the Visual Studio extensions directory, typically:
C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\16.0_xxxxxx\Extensions\

[micro-profiler_frontend.zip](https://github.com/tyoma/micro-profiler/files/3422047/micro-profiler_frontend.zip)

**Comment by pk1954** [comment]
Hi Artem,
1. I saved the stats and loaded them as you proposed. A second tab opens with identical behavior. Rings are visible, no lists.
2. I replaced the frontend dll with your new version. No change. Same effect as before.
3. I have to admit a "misdeed" you should know about: Before I posted the issue I desperately browsed through this forum and found an (old) post with a similar issue. The user resolved his problem by erasing some registry entries. I tried the same and deleted every registry entry regarding microprofiler. It didn't help, but also didn't make things worse. Later I tried to reinstall microprofiler to have a clean installation again, but the VSIX installer refused to work, because microprofiler is already installed. Tried to deinstall it, but doesn't show up in windows apps & features list. What is the proper way to deinstall microprofiler? 
Thank you for your support
Peter

**Comment by tyoma** [comment]
Hi Peter,

Thank you so much for the feedback!
I'm going to add logging to resolve the situation. This will be done in 1-2 weeks. Will you be able to run it then?
To uninstall extension you have to go to Extensions -> Manage Extensions and there, in the list of extensions, click Uninstall. The registry issue is unrelated - it's about the off-screen placement of profiler's window in a standalone mode.

Thanks again!

**Comment by pk1954** [comment]
Hi Artem,
of course I will run any new version as soon as possible. I'm looking forward to test microprofiler.
Thank you
Peter

**Comment by pk1954** [comment]
Hi,
some additional info: 
I wondered, if there is something special with my application causing the problem. So I created a new empty project from scratch -> same situation, no lists.
My app is using pure win32 API, unmanaged code.  I'm an old C hacker veteran and don't like all this modern .NET stuff. I use C++ but still with a lot of bad C habits.
Finally I brought myself to create a new Wpf application just out of curiosity: Tried to enable profiling -> "Visual Studio has encountered an unexpected error". I suspect, something is wrong with .NET on my machine, although Visual Studio Installer says everything is ok.
I will come back to you, if I can found out more.
Peter

**Comment by pk1954** [comment]
Hi Artem,
now I'm really perplexed. My assumption was, that something strange is bad with my development machine. So I took another machine (an old notebook a normally use only for browsing), installed Visual Studio from scratch and also microprofiler. Same behavior! Missing lists in microprofiler frontend, WPF application: Error when trying to enable profiling.
I can not imagine, what could be special with these two machines.
This means, you should be able to reproduce the issue on a clean machine. 
At this point I stop my investigation and look forward to a new version of microprofiler.
Best regards
Peter

**Comment by tyoma** [comment]
Thanks Peter! The strange thing is that I'm testing on exactly the same version of Visual Studio - 16.1.6.
The lists are regular Windows SysListView32 controls [subclassed with my own message procedure](https://github.com/tyoma/wpl/blob/master/src/wpl.ui/win32/window.cpp#L62).

My initial guess was that windows were not created bc of the manifests, so I've added explicit active context activation - that was the dll I sent before. But even if that was true - you'd get errors (exceptions inside the code) bc of a failed window creation.

My other guess was that initialization logic/menu items handling is being invoked from non-main thread (I've recently reworked extension initialization to be conformant to new async package model that Visual Studio demands) - but that's barely possible, as I explicitely require [UI-thread context for these things](https://github.com/tyoma/micro-profiler/blob/classic/micro-profiler/visualstudio/vs-extension/vs-package.cpp#L71). But should that be true - you'd have no pie visible (and clickable).

It seems that somehow the lists get created but don't appear on surface of the Visual Studio pane - maybe the reason is [window reparenting](https://github.com/tyoma/wpl/blob/master/src/wpl.ui/win32/view_host.cpp#L240).

Can you tell the exact version of Windows you're using (type 'ver' in command line)? Maybe it doesn't allow reparenting the way I'm performing it...

P.S. WPF is a managed .Net framework, and micro-profiler don't support managed apps. I should've been more careful with handling of the 'Enable ...' menus on managed projects, though.

**Comment by t-gabor** [comment]
Hi,
Just want to add, I experience the same.
Using VS 2019(16.1.6), and v1.4.606. Microsoft Windows [Version 10.0.18362.175]
I had to reinstalled my machine this week, previously it was working, using v1.4.605 and VS2019.
Reverting back to v1.4.605 did not solve the problem now.

Thanks,
Gabor

**Comment by pk1954** [comment]
Hi,
I use Microsoft Windows [Version 10.0.18362.239]
Peter

**Comment by pk1954** [comment]
By the way: I just installed vs 16.2.0. Same behavior as before.
Peter

**Comment by tyoma** [comment]
@pk1954, @t-gabor - thanks guys! It seems that that the reason is that windowing scheme I use doesn't play well with newer version of Windows (I have quite an old build - 16299, as Windows fails to update on my macbook+bootcamp).
Will try to upgrade or get another machine.

**Comment by t-gabor** [comment]
@tyoma I managed to build and debug your code from github locally, but have no idea what to look for. Do you have any suggestions what should I try?

**Comment by tyoma** [comment]
@t-gabor, you can start debugging, open saved stats and check if [this is working fine](https://github.com/tyoma/wpl/blob/master/src/wpl.ui/win32/view_host.cpp#L236).

UPD: I've installed latest Windows update and guess what:
![image](https://user-images.githubusercontent.com/383348/61882051-5ad0b980-af00-11e9-8c90-d5ac934a5372.png)

**Comment by tyoma** [comment]
Right, [this line](https://github.com/tyoma/wpl/blob/master/src/wpl.ui/win32/view_host.cpp#L240) fails for SysListView32. I need to think on another approach of reconstructing the control.
thanks guys!

**Comment by tyoma** [comment]
Guys, please try the latest version from here: https://github.com/tyoma/micro-profiler/releases/tag/v1.4.607.0 (download and install vsix file).
It now works on my Windows 10 (May2019) machine.
Thank you!

**Comment by pk1954** [comment]
It works. Thank you!

**Comment by tyoma** [comment]
@pk1954, @t-gabor Peter, Gabor if it's not a big thing for you, please leave a review on [marketplace](https://marketplace.visualstudio.com/items?itemName=ArtemGevorkyan.MicroProfilerx64x86), if you find micro-profiler useful.
thanks!
